from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from typing import List, Optional
import io

from app.database import get_db
from app import models, schemas
from app.routers.auth import get_current_user

router = APIRouter(
    prefix="/reports",
    tags=["Reports Management"]
)

@router.get("")
def get_reports(
    search: Optional[str] = None,
    tag: Optional[str] = None,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    # Query reports associated with user's cases
    query = db.query(models.Report).join(
        models.Case, models.Report.case_id == models.Case.id
    ).filter(models.Case.user_id == current_user.id)

    if tag and tag != "All":
        # JSON contains check — works for Postgres JSONB / JSON arrays
        query = query.filter(models.Report.tags.contains([tag]))

    if search:
        query = query.filter(
            models.Report.title.ilike(f"%{search}%") |
            models.Report.caseTitle.ilike(f"%{search}%") |
            models.Report.caseNumber.ilike(f"%{search}%")
        )

    reports = query.order_by(models.Report.created_at.desc()).all()

    def _ser(r):
        return {
            "id": r.id,
            "title": r.title,
            "caseNumber": r.caseNumber,
            "caseTitle": r.caseTitle,
            "type": r.type,
            "authorAgent": r.authorAgent,
            "generatedDate": r.generatedDate,
            "fileSize": r.fileSize,
            "pages": r.pages,
            "riskScore": r.riskScore,
            "successProbability": r.successProbability,
            "summary": r.summary,
            "downloadUrl": r.downloadUrl,
            "tags": r.tags or [],
        }

    return {"success": True, "data": [_ser(r) for r in reports]}

@router.get("/download/{case_id}")
def download_report(
    case_id: str,
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user)
):
    # Fetch case and report details
    case = db.query(models.Case).filter(
        models.Case.id == case_id,
        models.Case.user_id == current_user.id
    ).first()
    
    if not case:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Report or associated case not found."
        )
        
    report = db.query(models.Report).filter(models.Report.case_id == case_id).first()
    
    # Generate a simple text-based dummy PDF stream for immediate download
    report_text = f"""
========================================================================
                      LEXINTEL AI LEGAL DOSSIER
========================================================================
Case Number: {case.caseNumber}
Case Title: {case.title}
Jurisdiction: {case.jurisdiction}
Filing Date: {case.filingDate}
Litigant: {case.clientName}
Respondent: {case.opposingParty}

------------------------------------------------------------------------
SUMMARY ASSESSMENT:
{case.summary}

------------------------------------------------------------------------
OUTCOME ESTIMATES:
- Success Probability: {case.successProbability}%
- Settlement Chance: {case.settlementChance}%
- Risk Score: {case.riskScore}/100 ({case.riskLevel} Risk)

------------------------------------------------------------------------
APPLICABLE LAWS AND STATUTES:
{chr(10).join([f'- {law}' for law in (case.applicableLaws or [])])}

------------------------------------------------------------------------
COUNSEL STRATEGY ROADMAP:
{chr(10).join([f'{i+1}. {strat}' for i, strat in enumerate(case.defenseStrategy or [])])}

------------------------------------------------------------------------
GENERATED NOTICE DRAFT:
{case.generatedNotice}

========================================================================
Generated by LexIntel AI Platform. Date: {report.generatedDate if report else 'July 2026'}.
This report is an AI estimation and does not constitute certified legal advice.
========================================================================
"""
    # Create an in-memory text stream representing a PDF
    buffer = io.BytesIO()
    buffer.write(report_text.encode('utf-8'))
    buffer.seek(0)
    
    headers = {
        'Content-Disposition': f'attachment; filename="LexIntel_Dossier_{case.caseNumber.replace("/", "_")}.pdf"'
    }
    
    # Send as plain text file disguised as attachment for mock simplicity
    return StreamingResponse(buffer, media_type="text/plain", headers=headers)
